version: '3.8'
services:
  flight_controller_bridge:
    build: ./flight_controller_bridge
    ports:
      - "5100:5100"
  mission_planner:
    build: ./mission_planner
    ports:
      - "5200:5200"
  sensor_fusion:
    build: ./sensor_fusion
    ports:
      - "5300:5300"
  swarm_comm_broker:
    build: ./swarm_comm_broker
    ports:
      - "5400:5400"
      - "5401:5401"
  security_layer:
    build: ./security_layer
    ports:
      - "5450:5450"
  latency_predictor:
    build: ./latency_predictor
    ports:
      - "5500:5500"
  video_encryption:
    build: ./video_encryption
    ports:
      - "5600:5600"
  swarm_ai:
    build: ./swarm_ai
    ports:
      - "5700:5700" 